### ISSUE TITLE
1.19.4 Crashes when bees headbutt. Cannot load worlds without mod after removal.

### ISSUE THREAD

**Issue by SarahNerd** [HyperPigeon/BeeDance#1]
Here is my latest log and crash report.

[latest.log](https://github.com/HyperPigeon/BeeDance/files/11750087/latest.log)
[crash-2023-06-14_16.04.25-server.txt](https://github.com/HyperPigeon/BeeDance/files/11750096/crash-2023-06-14_16.04.25-server.txt)

**Comment by SarahNerd** [comment]
Update: Not being able to load without the mod was a Prism (client) issue. The headbutt attempt then crash still occurs.

**Comment by HyperPigeon** [comment]
Sorry that this took so long to address, I've pushed an update to the 1.19.4 version that should fix the issue. Let me know if you run into it again.
